spring:
  application:
    jwt:
      cookie:
        name: token
      expiration:
        ms: 10800000
      secret: 0123456789012345678901234567890123456789012345678901234567890123

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,metrics,info'

  logging:
    file:
      name: ./logs/crud_users_and_auth.log

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false

  sql:
    init:
      mode: never

  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.globally_quoted_identifiers: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password:
    debug: false
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080