spring:
  application:
    jwt:
      cookie:
        name: token
      expiration:
        ms: 10800000
      secret: 0123456789012345678901234567890123456789012345678901234567890123

  data:
    mongodb:
      host: "localhost"
      port: 27017
      database:

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false

  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        globally_quoted_identifiers: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    debug: true
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: ./logs/crud_users_and_auth.log

server:
  port: 8080